# Generated by Django 4.2.1 on 2023-08-17 23:07

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="model",
            options={"ordering": ["id"]},
        ),
        migrations.AlterField(
            model_name="model",
            name="license",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="model",
            name="license_link",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="model",
            name="link",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="model",
            name="model_gltf_file",
            field=models.FileField(
                default="pendulum.gltf", upload_to=backend.models.custom_upload_function
            ),
        ),
    ]
